# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2afd641bcb61d434872d0ad14a24fbf8"
name = "Hubcodespace Sitemap Builder"
handle = "hubcodespace-sitemap-builder"
application_url = "https://sitemap-builder.hubcode.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products"

[auth]
redirect_urls = [
  "https://sitemap-builder.hubcode.dev/auth/callback",
  "https://sitemap-builder.hubcode.dev/auth/shopify/callback",
  "https://sitemap-builder.hubcode.dev/api/auth/callback"
]

[app_proxy]
url = "https://iraq-ind-luke-fly.trycloudflare.com/sitemap"
subpath = "hubcodespace-sitemap-builder"
prefix = "apps"

[pos]
embedded = false
